In [ ]:
#pandas:is is ope source python library built in the top of numpy

In [29]:
#Import basic libraries
import numpy as np;
import pandas as pd;

In [3]:
#creating a empty series
A=pd.Series()
A

Series([], dtype: object)

In [5]:
#create a series with single element
B=pd.Series("Hello")
B

0    Hello
dtype: object

In [7]:
#create a series using list

colors=["blue","yellow","orange","white"]
print(pd.Series(colors))

0      blue
1    yellow
2    orange
3     white
dtype: object

In [8]:
#create a series using tuple
tuple=[1000,2000,3000,4000,5000]
print(pd.Series(tuple))

0    1000
1    2000
2    3000
3    4000
4    5000
dtype: int64

In [9]:
#create series using dict
dict={101:"John",102:"Mary",103:"zara",104:"Ridaa"}
print(pd.Series(dict))

101     John
102     Mary
103     zara
104    Ridaa
dtype: object

In [11]:
A=pd.Series(["Monday","Tuesday","Wednesday","Thursday"])
print(A)

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
dtype: object

In [14]:
#change the index values
A.index=["day1","day2","day3","day4"]
print(A)

day1       Monday
day2      Tuesday
day3    Wednesday
day4     Thursday
dtype: object

In [16]:
#fetch monday
A["day1"]

'Monday'

#Data Frames:is a 2Dimentional data structures
* it stores the value in the form of tabular fashion i-e rows n columns
##features of data frames:
* columns are of different data types
* it will have labelled axes(row & columns)
* we can access values rows n columns
* can perform arithematic operations on rows n columns

## syntax is:pd.DataFrame(data,index,columns,dtype) where d n f should b capital

In [18]:
#create a dataframe using nested list

data =[[1,2,3],[4,5,6],[7,8,9]];
A=pd.DataFrame(data)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [24]:
list=[["john",40],["Mary",50],["Arshi",60],["Aalim",40]]
B=pd.DataFrame(list,columns=["Name","Age"],index=[101,102,103,104])
B

      Name  Age
101   john   40
102   Mary   50
103  Arshi   60
104  Aalim   40

In [32]:
# creating a dataframe using dict

dict={"Name":["John","Mary","Zara","Ridaa","Arshi"],"Age":[40,50,60,20,30],"Job":["HR","Manager","Analyst","Teacher","Engineer"],"Salary":[30000,40000,50000,20000,60000]}

In [34]:
d=pd.DataFrame(dict,index=[101,102,103,104,105])
d

      Name  Age       Job  Salary
101   John   40        HR   30000
102   Mary   50   Manager   40000
103   Zara   60   Analyst   50000
104  Ridaa   20   Teacher   20000
105  Arshi   30  Engineer   60000

In [36]:
#creating a dataframe using nested list

list=[["Apple",20],["Orange",30,120],["Banana",40]]
nestedList =pd.DataFrame(list,columns=["Fruits","No_of_fruits","fruits_per_kilo"])
nestedList # if we dnt have  equal no of values then it will be taken as NAN,null,none values(missing values)

   Fruits  No_of_fruits  fruits_per_kilo
0   Apple            20              NaN
1  Orange            30            120.0
2  Banana            40              NaN

In [46]:
#how to sort data
d
d.sort_values("Salary") # by deafault its in ascending value
d.sort_values("Salary",ascending=False,inplace=True)
d

      Name  Age       Job  Salary
105  Arshi   30  Engineer   60000
103   Zara   60   Analyst   50000
102   Mary   50   Manager   40000
101   John   40        HR   30000
104  Ridaa   20   Teacher   20000

In [51]:
#To Sort in Ascending---By default it sorts in ascending order else just give the ascending=True
#To Sort in descending---give ascending =False
# To make permanent change--give inplace=True

#create a copy of data
#copy()-- it helps in creating original copy of data
copyData=d.copy()
copyData

#sort values based on age
copyData.sort_values("Age",inplace=True)
copyData

      Name  Age       Job  Salary
104  Ridaa   20   Teacher   20000
105  Arshi   30  Engineer   60000
101   John   40        HR   30000
102   Mary   50   Manager   40000
103   Zara   60   Analyst   50000

In [54]:
#How to fetch the columns and rows
#loc:loc function is used to fetch columns and rows based on cloumn name or index name.
#iloc:iloc function is used to fetch row and columns based on index position of rows and columns

In [55]:
#fetch column name
copyData[["Name"]]

      Name
104  Ridaa
105  Arshi
101   John
102   Mary
103   Zara

In [56]:
#fetch multiple column i-e Age,Salary
copyData[["Age","Salary"]]

     Age  Salary
104   20   20000
105   30   60000
101   40   30000
102   50   40000
103   60   50000

In [59]:
#we can fetch column name using loc func also
copyData.loc[:,["Name","Age"]]

      Name  Age
104  Ridaa   20
105  Arshi   30
101   John   40
102   Mary   50
103   Zara   60

In [62]:
#fetch age using loc func
copyData.loc[:,["Age"]]

     Age
104   20
105   30
101   40
102   50
103   60

In [63]:
#fetch name and salary using loc
copyData.loc[:,["Name","Salary"]]

      Name  Salary
104  Ridaa   20000
105  Arshi   60000
101   John   30000
102   Mary   40000
103   Zara   50000

In [67]:
#fetch first row names or index name
copyData.loc[[101],:]

     Name  Age Job  Salary
101  John   40  HR   30000

In [69]:
#fetch the second and third row
copyData.loc[[104,105],:]

      Name  Age       Job  Salary
104  Ridaa   20   Teacher   20000
105  Arshi   30  Engineer   60000

In [71]:
#fetch first row and last row

copyData.loc[[104,105],:]

      Name  Age       Job  Salary
104  Ridaa   20   Teacher   20000
105  Arshi   30  Engineer   60000

In [75]:
#fetch second third fourth and fifth row

copyData.loc[[102,103,104,105],:]
# using slicing
 # copyData.loc[102:106:,:] # it dosnt fetch beczz thr is miss continuety like 101,102,103,104,105 if it id 101,103,104,105,102 thn it is not possible

      Name  Age       Job  Salary
102   Mary   50   Manager   40000
103   Zara   60   Analyst   50000
104  Ridaa   20   Teacher   20000
105  Arshi   30  Engineer   60000

In [76]:
copyData

      Name  Age       Job  Salary
104  Ridaa   20   Teacher   20000
105  Arshi   30  Engineer   60000
101   John   40        HR   30000
102   Mary   50   Manager   40000
103   Zara   60   Analyst   50000

In [78]:
copyData.loc[[105,103,102],["Age","Job","Salary"]]

     Age       Job  Salary
105   30  Engineer   60000
103   60   Analyst   50000
102   50   Manager   40000

In [79]:
#iloc:
#fetch first column
copyData.iloc[:,[0]]

      Name
104  Ridaa
105  Arshi
101   John
102   Mary
103   Zara

In [82]:
#fetch the 3rd n 4th column
copyData.iloc[:,[2,3]]

          Job  Salary
104   Teacher   20000
105  Engineer   60000
101        HR   30000
102   Manager   40000
103   Analyst   50000

In [89]:
#fetch 2nd ,3rd and 4th column using slicing
#using slicing end value is not included we need to give extra one value to that n only one brackets is enough
copyData.iloc[:,1:4]

     Age       Job  Salary
104   20   Teacher   20000
105   30  Engineer   60000
101   40        HR   30000
102   50   Manager   40000
103   60   Analyst   50000

In [91]:
#fetch first row
copyData.iloc[[0],:]

      Name  Age      Job  Salary
104  Ridaa   20  Teacher   20000

In [96]:
#fetch 2nd n 3rd row using iloc
copyData.iloc[[1,2],:]

      Name  Age       Job  Salary
105  Arshi   30  Engineer   60000
101   John   40        HR   30000

In [97]:
#fetch 1,2,3,4 using iloc
copyData.iloc[[0,1,2,3],:]

      Name  Age       Job  Salary
104  Ridaa   20   Teacher   20000
105  Arshi   30  Engineer   60000
101   John   40        HR   30000
102   Mary   50   Manager   40000